security:
  providers:
    # enable the "ABAC" security provider (also handles RBAC)
    - abac:
    # enabled the HTTP Basic authentication provider
    - http-basic-auth:
        realm: "helidon"
        users:
          - login: "tim"
            password: "graves"
            roles: ["admin"]  
        #outbound:
        #  - name: "propogate-to-everyone"
        #    hosts: ["*"]